import pickle
from typing import List, Dict, Tuple
import numpy as np
from concurrent.futures import ProcessPoolExecutor
from arithmetic_compressor import AECompressor
from arithmetic_compressor.models import BaseFrequencyTable  # adaptive freq table

# Converting negative values to positive ones for better arithmetic coder performance
def zigzag_encode(x: int) -> int:
    return 2 * x if x >= 0 else -2 * x - 1

# Reverse zigzag
def zigzag_decode(z: int) -> int:
    return z // 2 if (z & 1) == 0 else -(z // 2) - 1

# Building adaptive model
def make_model(alphabet_size: int):
    if alphabet_size < 1:
        alphabet_size = 1
    p = 1.0 / alphabet_size
    probs = {i: p for i in range(alphabet_size)}
    return BaseFrequencyTable(probs)

# Encoding a single block
def entropy_encode(block: Dict) -> Dict:
    data = block['data']
    h, w = map(int, block['shape'])

    flat = data.reshape(-1).astype(np.int64, copy=False)
    # Scalar zig-zag to non-negative ints
    zz_list = list(map(zigzag_encode, flat.tolist()))
    max_symbol = max(zz_list) if zz_list else 0
    alphabet_size = max(max_symbol + 1, 1)

    model = make_model(alphabet_size)
    coder = AECompressor(model)
    encoded_bits = coder.compress(zz_list)

    return {
        'component': block['component'],
        'level':     block['level'],
        'band':      block['band'],
        'position':  block['position'],
        'shape':     [h, w],
        'alphabet_size': alphabet_size,
        'encoded_bits':  encoded_bits,
    }

# Decoding a songle block
def entropy_decode(block: Dict) -> Dict:
    h, w = map(int, block['shape'])
    n = h * w
    alphabet_size = block['alphabet_size']

    model = make_model(alphabet_size)
    coder = AECompressor(model)

    zz_list = coder.decompress(block['encoded_bits'], n) 
    vals = list(map(zigzag_decode, zz_list))
    data2d = np.array(vals, dtype=np.int32).reshape((h, w))

    return {
        'component': block['component'],
        'level':     block['level'],
        'band':      block['band'],
        'position':  block['position'],
        'shape':     [h, w],
        'data':      data2d,
    }

# Encode all blocks
def entropy_encode_all(blocks: List[Dict], output_path: str):
    with ProcessPoolExecutor() as executor:
        encoded = list(executor.map(entropy_encode, blocks))
    with open(output_path, 'wb') as f:
        pickle.dump(encoded, f, protocol=pickle.HIGHEST_PROTOCOL)

# Decode all blocks
def entropy_decode_all(input_path: str) -> List[Dict]:
    with open(input_path, 'rb') as f:
        encoded = pickle.load(f)
    with ProcessPoolExecutor() as executor:
        decoded = list(executor.map(entropy_decode, encoded))
    return decoded


# Test case generated by ChatGPT
if __name__ == "__main__":
    # Tiny smoke test with two fake blocks
    rng = np.random.default_rng(0)
    blk1 = {
        'component': 0, 'level': 0, 'band': 0, 'position': (0,0),
        'shape': [8, 8],
        'data': rng.integers(-3, 4, size=(8,8), dtype=np.int32)
    }
    blk2 = {
        'component': 0, 'level': 0, 'band': 1, 'position': (0,1),
        'shape': [8, 8],
        'data': rng.integers(-2, 3, size=(8,8), dtype=np.int32)
    }

    out_file = "blocks_ac.bin"
    entropy_encode_all([blk1, blk2], out_file)
    decoded_blocks = entropy_decode_all(out_file)

    for ref, dec in zip([blk1, blk2], decoded_blocks):
        assert np.array_equal(ref['data'], dec['data'])
    print("Round-trip OK.")
